# Generated by Django 4.0.2 on 2022-02-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(verbose_name='last update')),
                ('data', models.JSONField(verbose_name='json data')),
            ],
        ),
        migrations.RemoveField(
            model_name='episode',
            name='Episode',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.RemoveField(
            model_name='title',
            name='id',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='episode',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imdb_api.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imdb_api.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='imdb_api.item'),
            preserve_default=False,
        ),
    ]
